// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3w-QU9d-oDo_Vrfaar65mMrkAhbx3yK4',
    appId: '1:315056418916:web:21e44f215c4bd8e4b16f71',
    messagingSenderId: '315056418916',
    projectId: 'qr-checkin-app-efe91',
    authDomain: 'qr-checkin-app-efe91.firebaseapp.com',
    storageBucket: 'qr-checkin-app-efe91.firebasestorage.app',
    measurementId: 'G-JRXYJ55C91',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxw7_KpcWMBQUrNyCRLS15VVKe5TAJH1Y',
    appId: '1:315056418916:android:61565fd9666927e4b16f71',
    messagingSenderId: '315056418916',
    projectId: 'qr-checkin-app-efe91',
    storageBucket: 'qr-checkin-app-efe91.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYHB6u0hFVUc9l2nxS77m1tgzs5hc0d_M',
    appId: '1:315056418916:ios:e7825dad22a7406cb16f71',
    messagingSenderId: '315056418916',
    projectId: 'qr-checkin-app-efe91',
    storageBucket: 'qr-checkin-app-efe91.firebasestorage.app',
    iosBundleId: 'com.example.qrCheckinApp',
  );
}
